version: 0.2

phases:
  install:
    runtime_versions:
      nodejs: 20
    commands:
      - echo "Installing Orders service dependencies"
      - cd services/orders && npm ci
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - cd services/orders
      - echo "Running unit tests"
      - npm test
  build:
    commands:
      - echo "Building Orders Docker image"
      - cd ../..
      - docker build -t $ECR_REGISTRY/project6_orders:$CODEBUILD_RESOLVED_SOURCE_VERSION services/orders/
      - docker tag $ECR_REGISTRY/project6_orders:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REGISTRY/project6_orders:latest
      - echo "Pushing Docker image to ECR"
      - docker push $ECR_REGISTRY/project6_orders:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_REGISTRY/project6_orders:latest
  post_build:
    commands:
      - echo "Generating deployment artifacts for CodeDeploy"
      - bash deployment/scripts/generate_taskdef.sh orders $CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - deployment/task_definitions/orders_taskdef.json
    - deployment/appspec/orders_appspec.yml
